### ISSUE TITLE
Linux: LSP Attachment issue when buffer has 2 or more LSP attached to it

### ISSUE THREAD

**Issue by Callophrys** [JustBarnt/JustNvim#1]

**Comment by JustBarnt** [comment]
Should be resolved as the LSP setup has been reverted.

**Comment by JustBarnt** [comment]
This appears to still be an issue actually. Regardless of what the LSP's are. It just seems to need 2 more lsps to be an issue.

**Comment by JustBarnt** [comment]
@Callophrys Did some testing this weekend, I found that when creating the project or cloning the project from github directly into linux/wsl there are no issues, but if you try to open the project through wsl on a windows drive `tailwindcss-language-server` fails because it cannot find the related files it needs from skeleton and/or other tailwind files to correctly get the definitions being looked for. This could be fixed by creating a symlink to the files on windows. But I think it would be easier to just use the project via linux on WSL instead.

Alternatively, which I didn't test, I would expect you to be able to copy the project, delete the `node_modules` folder, and then run `npm/pnpm install`. That should also work.
